version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: docker-sav-node
    restart: always
    ports:
      # - 9229:9229
      # - 3001:3000
      - 8081:3030
    command: npm run start-dev
