version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: docker-sav-node
    restart: always
    ports:
      - 3030:3030
      - 9229:9229
    command: npm run start-dev
